DECLARE_POINTERS(IEditorView)
DECLARE_POINTERS(IEditorViewFactory)
DECLARE_POINTERS(IEditorViewWidgetFactory)
DECLARE_POINTERS(IEditorDataModel)
DECLARE_POINTERS(IEditorListener)
DECLARE_POINTERS(IEditorController)

DECLARE_POINTERS(IEditorContext)

DECLARE_POINTERS(CCurveEditorView)
DECLARE_POINTERS(CCurveEditorDataModel)
DECLARE_POINTERS(ICurveEditorListener)
DECLARE_POINTERS(CCurveEditorController)

DECLARE_POINTERS(ICurveEditorSplineDataModel)
DECLARE_POINTERS(ICurveEditorSplineController)
DECLARE_POINTERS(ICurveEditorSplineControllerFactory)
DECLARE_POINTERS(ICurveEditorSplineView)
DECLARE_POINTERS(ICurveEditorSplineViewFactory)

DECLARE_POINTERS(IEditorTool)
DECLARE_POINTERS(ICurveEditorTool)

DECLARE_POINTERS(CCurveEditorCurveView)
DECLARE_POINTERS(CCurveEditorKnotView)