DECLARE_POINTERS(IEditorView)
DECLARE_POINTERS(IEditorViewFactory)
DECLARE_POINTERS(IEditorViewWidgetFactory)
DECLARE_POINTERS(IEditorDataModel)
DECLARE_POINTERS(IEditorController)

DECLARE_POINTERS(IEditorContext);

DECLARE_POINTERS(CCurveEditorViewBase)
DECLARE_POINTERS(CCurveEditorView)
DECLARE_POINTERS(CCurveEditorDataModel)
DECLARE_POINTERS(ICurveEditorProtocol)
DECLARE_POINTERS(CCurveEditorController)

DECLARE_POINTERS(CCurveEditorSplineDataModel);
DECLARE_POINTERS(CCurveEditorFunctionSplineController);
DECLARE_POINTERS(CCurveEditorSplineView);