DECLARE_POINTERS(IEditorView)
DECLARE_POINTERS(IEditorViewFactory)
DECLARE_POINTERS(IEditorViewWidgetFactory)
DECLARE_POINTERS(IEditorDataModel)
DECLARE_POINTERS(IEditorListener)
DECLARE_POINTERS(IEditorController)

DECLARE_POINTERS(IEditorContext)

DECLARE_POINTERS(ICurveEditorView)
DECLARE_POINTERS(ICurveEditorDataModel)
DECLARE_POINTERS(ICurveEditorControllerListener)
DECLARE_POINTERS(ICurveEditorController)

DECLARE_POINTERS(ICurveEditorSplineDataModel)
DECLARE_POINTERS(ICurveEditorSplineController)
DECLARE_POINTERS(ICurveEditorSplineControllerFactory)
DECLARE_POINTERS(ICurveEditorSplineView)
DECLARE_POINTERS(ICurveEditorSplineViewFactory)

DECLARE_POINTERS(IEditorTool)
DECLARE_POINTERS(ICurveEditorTool)
DECLARE_POINTERS(ICurveEditorComponentTool)

DECLARE_POINTERS(CCurveEditorSplineViewBase)
DECLARE_POINTERS(CCurveEditorCurveView)
DECLARE_POINTERS(CCurveEditorKnotView)
DECLARE_POINTERS(CCurveEditorTangentView)